---
# Area
- name: area/ansible
  color: "72ccf3"
  description: >-
    Changes made in the ansible directory
- name: area/github
  color: "72ccf3"
  description: >-
    Changes made in the github directory
- name: area/module
  color: "72ccf3"
  description: >-
    Changes made in the module directory
- name: area/definitions
  color: "72ccf3"
  description: >-
    Changes made in the main or example definations
- name: area/documentation
  color: "72ccf3"
  description: >-
    Changes made in the documentation directory
- name: area/tasks
  color: "72ccf3"
  description: >-
    Changes made in the .task directory
- name: area/vscode
  color: "72ccf3"
  description: >-
    Changes made in the .VSCode directory
# Renovate
- name: renovate/ansible
  color: "ffc300"
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
- name: renovate/terraform
  color: "ffc300"
# Semantic Type
- name: "type/no-release"
  color: "6C483F"
  description: "Fix and improvement will not create a new release"
- name: type/patch
  color: "FFEC19"
  description: "Something isn't working"
- name: type/minor
  color: "FF9800"
  description: "New feature or request"
- name: type/major
  color: "F6412D"
  description: "Multiple breaking changes, and new features"
# Size
- name: size/XS
  color: "009900"
  description: >-
    Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: "77bb00"
  description: >-
    Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: "eebb00"
  description: >-
    Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: "ee9900"
  description: >-
    Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: "ee5500"
  description: >-
    Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: "ee0000"
  description: >-
    Denotes a PR that changes 1000+ lines, ignoring generated files.
# Issue Templates
- name: bug
  color: "ee0701"
- name: question
  color: "cc317c"
- name: enhancement
  color: "84b6eb"
# Uncategorized
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: link-checker
  color: "7B55D7"
