---
name: "🧳 Build Documentation"

on:
  workflow_call:
  #   inputs:
  #     build_id:
  #       required: true
  #       type: number
  #  ${{ inputs.build_id }}

jobs:
  build-documenation:
    name: "Build Documentation"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      # Has this workflow already commented on the PR?
      - name: Find Intial Comment
        uses: peter-evans/find-comment@v2
        id: initial-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Compiling Documentation

      - name: Comment on PR Compiling Documentation ${{ matrix.directory }}
        if: steps.initial-comment.outputs.comment-id == ''
        id: build-example-comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Compiling Documentation

      # Initial Workflow Comment Reference for Updates
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Compiling Documentation

      # Grab the Current Terraform Binaries
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.3

      # Clone the repo to the 'src' folder
      - name: Clone repository for analysis
        uses: actions/checkout@v3
        with:
          # ref: ${{ github.sha }}
          path: src

      - name: Update comment with Preping
        if: steps.fc.outputs.comment-id != '' && steps.init.outcome != 'success'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |

            - Initializing documentation toolchain.

          edit-mode: append
          reactions: rocket

      ##
      ## STAGE 1 - Terraform Init
      ##

      - name: Setup pandoc
        env:
          PANDOC_VERSION: "2.18"
        run: |
          wget -qO- "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux-amd64.tar.gz" | sudo tar xzf - --strip-components 1 -C "/usr/local/"

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            ae
            amscls
            amsmath
            babel
            babel-english
            babel-german
            babelbib
            bookmark
            carlisle
            colortbl
            fancyhdr
            fix2col
            geometry
            graphics
            graphics-cfg
            hyperref
            latex
            latex-bin
            latex-fonts
            latexconfig
            ltxmisc
            mfnfss
            mptopdf
            natbib
            oberdiek
            pslatex
            psnfss
            pspicture
            tools
            url
            anysize
            beamer
            booktabs
            breqn
            caption
            cite
            cmap
            crop
            ctable
            eso-pic
            euenc
            euler
            etoolbox
            extsizes
            fancybox
            fancyref
            fancyvrb
            filehook
            float
            fontspec
            fp
            index
            jknapltx
            koma-script
            latexbug
            l3experimental
            l3kernel
            l3packages
            lineno
            listings
            lwarp
            mathspec
            mathtools
            mdwtools
            memoir
            metalogo
            microtype
            ms
            ntgclass
            parskip
            pdfpages
            polyglossia
            powerdot
            psfrag
            rcs
            sansmath
            section
            seminar
            sepnum
            setspace
            subfig
            textcase
            thumbpdf
            translator
            typehtml
            ucharcat
            underscore
            unicode-math
            xcolor
            xkeyval
            xltxtra
            xunicode
            adjustbox
            background
            bidi
            collectbox
            csquotes
            everypage
            filehook
            footmisc
            footnotebackref
            framed
            fvextra
            letltxmacro
            ly1
            mdframed
            mweights
            needspace
            pagecolor
            sourcecodepro
            sourcesanspro
            titling
            ucharcat
            ulem
            unicode-math
            upquote
            xecjk
            xurl
            zref
            awesomebox
            fontawesome5
            tcolorbox
            pgf
            etoolbox
            environ
            trimspaces
            lastpage
            enumitem

      - name: Initialization for tlmgr
        run: |
          sudo apt-get update -qq && sudo apt-get install xzdec -y
          tlmgr init-usertree

      - name: Setup fonts and image conversion tool
        run: sudo apt-get update -qq && sudo apt-get install fonts-noto-cjk poppler-utils fonts-crosextra-carlito fonts-crosextra-caladea -y

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install python filters
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-latex-environment

      - name: Build PDF
        shell: pwsh
        run: |
          $Global:ProgressPreference = 'SilentlyContinue';
          & docs/build.ps1 -OrderFile markdown/design-document.order -MetadataFile markdown/design-document.yaml -Template templates/design-document.tex -OutFile design-document.pdf

      - name: Publish PDF
        uses: actions/upload-artifact@v2
        with:
          name: docs
          if-no-files-found: error
          retention-days: 5
          path: "${{ github.workspace }}/design-document.pdf"
